# Generated by Django 4.1.3 on 2023-07-02 23:46

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Productor'), (2, 'Affiliated'), (3, 'Pay'), (4, 'Seller')], default=1)),
                ('date', models.DateTimeField()),
                ('product', models.CharField(max_length=30)),
                ('value', models.IntegerField(default=0)),
                ('seller', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['id'],
            },
        ),
    ]
